version: "3.9"

services:
  redis:
    image: redis:7.0.2-alpine3.16
    container_name: redis
    ports:
      - "6379:6379"

  hit_counter:
    build:
      context: ./hit_counter
      dockerfile: Dockerfile
    command: sh -c "cd /usr && python -m src"
    container_name: hit_counter
    links:
      - "redis"
    ports:
      - "3000:3000"
